export type VisualTone = 'violet' | 'amber' | 'rose' | 'blue' | 'green'
export interface ProductVisualRule {
  id: string
  emoji: string
  tone: VisualTone
  family: string
  aliases: string[]
  priority: number
}
type Entry = [id: string, emoji: string, tone: VisualTone, aliases: string, priority?: number]
function family(name: string, priority: number, entries: Entry[]): ProductVisualRule[] {
  return entries.map(([id, emoji, tone, aliases, override]) => ({ id, emoji, tone, family: name, aliases: aliases.split('|'), priority: override ?? priority }))
}

/** Curated visual hints, not product identities or accounting categories. */
export const PRODUCT_VISUAL_CATALOG: ProductVisualRule[] = [
  ...family('Fruit & vegetables', 0, [
    ['grapes','🍇','violet','grape|grapes|عنب'],
    ['apple','🍎','rose','apple|apples|تفاح'],
    ['green-apple','🍏','green','green apple|green apples|تفاح اخضر'],
    ['banana','🍌','amber','banana|bananas|موز'],
    ['orange','🍊','amber','orange|oranges|برتقال'],
    ['mandarin','🍊','amber','mandarin|tangerine|يوسفي|يوسفى'],
    ['lemon','🍋','amber','lemon|lemons|ليمون'],
    ['lime','🍋','green','lime|limes|ليمون اخضر'],
    ['strawberry','🍓','rose','strawberry|strawberries|فراوله|فراولة'],
    ['watermelon','🍉','green','watermelon|بطيخ'],
    ['melon','🍈','green','melon|cantaloupe|كنتالوب|شمام'],
    ['peach','🍑','rose','peach|peaches|خوخ'],
    ['pear','🍐','green','pear|pears|كمثري|كمثرى'],
    ['pineapple','🍍','amber','pineapple|اناناس'],
    ['mango','🥭','amber','mango|mangoes|mangos|مانجو|مانجا'],
    ['cherry','🍒','rose','cherry|cherries|كرز'],
    ['blueberry','🫐','blue','blueberry|blueberries|توت ازرق'],
    ['berries','🫐','violet','berries|raspberry|blackberry|توت'],
    ['kiwi','🥝','green','kiwi|كيوي'],
    ['coconut','🥥','amber','coconut|جوز الهند'],
    ['avocado','🥑','green','avocado|avocados|افوكادو'],
    ['plum','🟣','violet','plum|plums|barquq|برقوق'],
    ['apricot','🍑','amber','apricot|apricots|مشمش'],
    ['dates','🌴','amber','dates|medjool|تمر|بلح'],
    ['fig','🌳','green','fig|figs|تين'],
    ['pomegranate','🍎','rose','pomegranate|رمان'],
    ['guava','🍐','green','guava|جوافه|جوافة'],
    ['tomato','🍅','rose','tomato|tomatoes|طماطم'],
    ['potato','🥔','amber','potato|potatoes|بطاطس'],
    ['sweet-potato','🍠','amber','sweet potato|sweet potatoes|بطاطا'],
    ['carrot','🥕','amber','carrot|carrots|جزر'],
    ['cucumber','🥒','green','cucumber|cucumbers|خيار'],
    ['onion','🧅','amber','onion|onions|بصل'],
    ['garlic','🧄','amber','garlic|ثوم|توم'],
    ['eggplant','🍆','violet','eggplant|aubergine|باذنجان|بتنجان'],
    ['pepper','🫑','green','bell pepper|bell peppers|فلفل رومي|فلفل الوان'],
    ['chilli','🌶️','rose','chili|chilli|chillies|فلفل حار'],
    ['broccoli','🥦','green','broccoli|بروكلي|بروكلى'],
    ['cauliflower','🥦','green','cauliflower|قرنبيط'],
    ['cabbage','🥬','green','cabbage|كرنب'],
    ['lettuce','🥬','green','lettuce|خس'],
    ['spinach','🥬','green','spinach|سبانخ'],
    ['molokhia','🥬','green','molokhia|molokheya|molokhiya|ملوخيه|ملوخية'],
    ['zucchini','🥒','green','zucchini|courgette|كوسه|كوسة'],
    ['peas','🫛','green','peas|بسله|بسلة|بازلاء'],
    ['green-beans','🫛','green','green beans|فاصوليا خضرا|فاصوليا خضراء',20],
    ['okra','🫛','green','okra|باميه|بامية'],
    ['corn','🌽','amber','corn|sweetcorn|ذره|ذرة'],
    ['mushroom','🍄','amber','mushroom|mushrooms|مشروم|عيش الغراب'],
    ['pumpkin','🎃','amber','pumpkin|قرع'],
    ['beetroot','🥬','rose','beetroot|beets|بنجر'],
    ['radish','🥬','rose','radish|فجل'],
    ['celery','🌿','green','celery|كرفس'],
    ['parsley','🌿','green','parsley|بقدونس'],
    ['coriander','🌿','green','coriander|cilantro|كزبره|كزبرة'],
    ['dill','🌿','green','dill|شبت'],
    ['mint','🌿','green','mint|نعناع'],
    ['basil','🌿','green','basil|ريحان'],
    ['rocket','🥬','green','arugula|rocket leaves|جرجير|greenery'],
    ['ginger','🫚','amber','ginger|جنزبيل|زنجبيل'],
    ['artichoke','🥬','green','artichoke|خرشوف'],
    ['leek','🥬','green','leek|leeks|كراث'],
  ]),
  ...family('Meat, fish & eggs', 5, [
    ['beef','🥩','rose','beef|meat|steak|لحم|لحمه|لحمة|لحوم'],
    ['mince','🥩','rose','minced meat|ground beef|لحم مفروم|لحمه مفرومه'],
    ['lamb','🥩','rose','lamb|mutton|لحم ضاني|ضاني'],
    ['chicken','🍗','amber','chicken|poultry|دجاج|فراخ|dagag|دبوس دجاج|dabosa dagag'],
    ['turkey','🍗','amber','turkey|ديك رومي'],
    ['duck','🦆','amber','duck|بط'],
    ['fish','🐟','blue','fish|سمك|اسماك'],
    ['salmon','🍣','rose','salmon|سلمون'],
    ['tuna','🐟','blue','tuna|تونه|تونة'],
    ['sardines','🐟','blue','sardines|سردين'],
    ['shrimp','🍤','rose','shrimp|prawns|جمبري|جمبرى'],
    ['squid','🦑','violet','squid|calamari|سبيط|كاليماري'],
    ['crab','🦀','rose','crab|كابوريا'],
    ['lobster','🦞','rose','lobster|استاكوزا'],
    ['oyster','🦪','blue','oyster|oysters|محار'],
    ['eggs','🥚','amber','egg|eggs|بيض'],
    ['liver','🥩','rose','liver|كبده|كبدة'],
    ['sausage','🌭','rose','sausage|sausages|سجق'],
    ['bacon','🥓','rose','bacon|بيكون'],
    ['luncheon','🥪','rose','luncheon|mortadella|لانشون|مرتديلا'],
    ['pastrami','🥩','rose','pastrami|بسطرمه|بسطرمة'],
  ]),
  ...family('Dairy & chilled', 30, [
    ['milk','🥛','blue','milk|لبن|حليب'],
    ['plant-milk','🥛','green','almond milk|oat milk|soy milk|coconut milk|حليب لوز|حليب شوفان|حليب جوز الهند',35],
    ['yogurt','🥛','blue','yogurt|yoghurt|زبادي|زبادى|zabadi'],
    ['greek-yogurt','🥛','blue','greek yogurt|greek yoghurt|زبادي يوناني'],
    ['cheese','🧀','amber','cheese|جبن|جبنه|جبنة|domti|دومتي'],
    ['cream-cheese','🧀','amber','cream cheese|creamy cheese|جبنه كريمي|جبن كريمي'],
    ['mozzarella','🧀','amber','mozzarella|موتزاريلا|موزاريلا'],
    ['cheddar','🧀','amber','cheddar|شيدر'],
    ['feta','🧀','amber','feta|فيتا'],
    ['roumy-cheese','🧀','amber','roumy|romi cheese|جبنه رومي|جبن رومي'],
    ['cottage-cheese','🧀','amber','cottage cheese|جبنه قريش|جبن قريش'],
    ['butter','🧈','amber','butter|زبده|زبدة'],
    ['ghee','🧈','amber','ghee|سمن|سمنه|سمنة'],
    ['cream','🥛','amber','cooking cream|whipping cream|كريمه طبخ|كريمة طبخ|قشطه|قشطة'],
    ['labneh','🥛','blue','labneh|لبنه|لبنة'],
    ['kefir','🥛','blue','kefir|كفير'],
    ['condensed-milk','🥛','amber','condensed milk|لبن مكثف|حليب مكثف'],
    ['milk-powder','🥛','blue','milk powder|powdered milk|لبن بودره|لبن بودرة|nido|نيدو'],
  ]),
  ...family('Bakery & breakfast', 20, [
    ['bread','🍞','amber','bread|عيش|خبز|rich bake|ريتش بيك'],
    ['toast','🍞','amber','toast|توست'],
    ['baguette','🥖','amber','baguette|باجيت'],
    ['croissant','🥐','amber','croissant|كرواسون'],
    ['bagel','🥯','amber','bagel|بيجل'],
    ['pretzel','🥨','amber','pretzel|بريتزل'],
    ['pancakes','🥞','amber','pancake|pancakes|بان كيك'],
    ['waffles','🧇','amber','waffle|waffles|وافل'],
    ['oats','🥣','amber','oats|oatmeal|شوفان'],
    ['cereal','🥣','amber','cereal|cornflakes|corn flakes|كورن فليكس'],
    ['granola','🥣','amber','granola|muesli|جرانولا|ميوسلي'],
    ['honey','🍯','amber','honey|عسل'],
    ['jam','🫙','rose','jam|marmalade|مربي|مربى'],
    ['peanut-butter','🥜','amber','peanut butter|زبده فول سوداني|زبدة فول سوداني',40],
    ['chocolate-spread','🍫','amber','chocolate spread|nutella|نوتيلا',40],
    ['tahini','🫙','amber','tahini|طحينه|طحينة'],
    ['halva','🍯','amber','halva|halawa|حلاوه طحينيه|حلاوة طحينية'],
    ['molasses','🍯','amber','molasses|عسل اسود|دبس'],
    ['rusk','🍞','amber','rusk|rusks|بقسماط'],
    ['tortilla','🫓','amber','tortilla|تورتيلا'],
  ]),
  ...family('Pantry & cooking', 15, [
    ['rice','🍚','amber','rice|ارز|رز'],
    ['pasta','🍝','amber','pasta|macaroni|spaghetti|penne|مكرونة|معكرونة'],
    ['noodles','🍜','amber','noodles|ramen|indomie|اندومي|نودلز'],
    ['flour','🌾','amber','flour|دقيق'],
    ['sugar','🍬','amber','sugar|سكر'],
    ['salt','🧂','blue','salt|ملح'],
    ['black-pepper','🧂','amber','black pepper|فلفل اسود'],
    ['cumin','🧂','amber','cumin|كمون'],
    ['cinnamon','🪵','amber','cinnamon|قرفه|قرفة'],
    ['turmeric','🧂','amber','turmeric|كركم'],
    ['paprika','🌶️','rose','paprika|بابريكا'],
    ['spices','🧂','amber','spices|seasoning|بهارات|توابل|خلطه|خلطة',50],
    ['cooking-oil','🫗','amber','cooking oil|sunflower oil|corn oil|oil|زيت|زيت ذرة|زيت عباد الشمس'],
    ['olive-oil','🫒','green','olive oil|زيت زيتون'],
    ['olives','🫒','green','olive|olives|زيتون'],
    ['vinegar','🫗','amber','vinegar|خل'],
    ['lentils','🫘','amber','lentil|lentils|عدس'],
    ['beans','🫘','amber','beans|bean|فول|لوبيا|فاصوليا'],
    ['chickpeas','🫘','amber','chickpeas|حمص'],
    ['bulgur','🌾','amber','bulgur|برغل'],
    ['freekeh','🌾','green','freekeh|freek|freeek|فريك'],
    ['quinoa','🌾','amber','quinoa|كينوا'],
    ['couscous','🍚','amber','couscous|كسكسي|كسكس'],
    ['starch','🌾','amber','corn starch|cornstarch|نشا'],
    ['baking-powder','🥣','blue','baking powder|biking powder|بيكنج بودر'],
    ['baking-soda','🥣','blue','baking soda|بيكنج صودا|بيكربونات'],
    ['yeast','🍞','amber','yeast|خميره|خميرة'],
    ['vanilla','🌼','amber','vanilla|فانيليا'],
    ['cocoa','🍫','amber','cocoa|كاكاو'],
    ['stock-cubes','🍲','amber','stock cubes|bouillon|chicken stock|مرقه|مرقة|mr2et dagag'],
    ['tomato-paste','🥫','rose','tomato paste|tomato puree|معجون طماطم|صلصه طماطم|صلصة طماطم',35],
    ['ketchup','🥫','rose','ketchup|katcheb|كاتشب',35],
    ['mayonnaise','🫙','amber','mayonnaise|mayo|مايونيز',35],
    ['mustard','🫙','amber','mustard|مسترده|مستردة',35],
    ['sauce','🥫','rose','sauce|souse|صلصه|صلصة|صوص',35],
    ['soy-sauce','🥫','amber','soy sauce|صويا صوص',36],
    ['pickles','🫙','green','pickles|مخلل|طرشي'],
    ['peanuts','🥜','amber','peanut|peanuts|فول سوداني'],
    ['almonds','🥜','amber','almond|almonds|لوز'],
    ['cashews','🥜','amber','cashew|cashews|كاجو'],
    ['pistachios','🥜','green','pistachio|pistachios|فستق'],
    ['walnuts','🥜','amber','walnut|walnuts|عين جمل'],
    ['hazelnuts','🥜','amber','hazelnut|hazelnuts|بندق'],
    ['seeds','🌻','amber','sunflower seeds|pumpkin seeds|لب سوري|لب ابيض|لب اسمر'],
    ['sesame','🌾','amber','sesame|سمسم'],
    ['raisins','🍇','violet','raisins|زبيب'],
    ['dried-fruit','🍑','amber','dried fruit|قراصيا|مشمشيه|مشمشية'],
  ]),
  ...family('Drinks & snacks', 40, [
    ['coffee','☕','amber','coffee|espresso|latte|cappuccino|lavazza|nescafe|قهوة|قهوه|نسكافيه'],
    ['tea','🍵','green','tea|شاي|شاى'],
    ['water','💧','blue','water|مياه|ماء|مياه معدنيه'],
    ['juice','🧃','amber','juice|عصير'],
    ['soda','🥤','rose','soda|cola|pepsi|sprite|fanta|بيبسي|كوكاكولا|سبرايت|فانتا'],
    ['smoothie','🥤','green','smoothie|سموذي'],
    ['milkshake','🥤','rose','milkshake|milk shake|ميلك شيك'],
    ['energy-drink','⚡','amber','energy drink|red bull|ريد بول|مشروب طاقه'],
    ['hot-chocolate','☕','amber','hot chocolate|هوت شوكليت',45],
    ['iced-tea','🧋','green','iced tea|ice tea|شاي مثلج',45],
    ['ice-cream','🍦','rose','ice cream|icecream|ايس كريم|آيس كريم',45],
    ['chocolate','🍫','amber','chocolate|شوكولاته|شوكولاتة|شيكولاته|galaxy|cadbury|kitkat'],
    ['cookies','🍪','amber','cookie|cookies|biscuit|biscuits|oreo|بسكويت|كوكيز|اوريو'],
    ['cake','🍰','rose','cake|كيك|كيكه|تورتة'],
    ['cheesecake','🍰','rose','cheesecake|cheese cake|تشيز كيك',45],
    ['doughnut','🍩','amber','donut|doughnut|دونات'],
    ['muffin','🧁','rose','muffin|cupcake|كب كيك|مافن'],
    ['popcorn','🍿','amber','popcorn|pop corn|فشار'],
    ['chips','🥔','amber','chips|crisps|chipsy|doritos|شيبسي|دوريتوس'],
    ['fries','🍟','amber','fries|french fries|بطاطس محمرة|بطاطس مقليه'],
    ['candy','🍬','rose','candy|sweets|bonbon|حلوي|حلوى|بونبون'],
    ['gum','🍬','green','chewing gum|لبان|علكه'],
    ['marshmallow','🍬','rose','marshmallow|مارشميلو'],
    ['kunafa','🥮','amber','kunafa|كنافه|كنافة'],
    ['basbousa','🥮','amber','basbousa|بسبوسه|بسبوسة'],
    ['baklava','🥮','amber','baklava|بقلاوه|بقلاوة'],
    ['balah-el-sham','🥮','amber','balah el sham|بلح الشام',45],
    ['pizza','🍕','rose','pizza|بيتزا'],
    ['burger','🍔','amber','burger|برجر'],
    ['sandwich','🥪','amber','sandwich|ساندوتش|سندوتش'],
    ['shawarma','🌯','amber','shawarma|شاورما'],
    ['falafel','🧆','green','falafel|taameya|طعمية|طعميه|فلافل'],
    ['koshary','🍲','amber','koshary|koshari|كشري|كشرى'],
    ['sushi','🍣','rose','sushi|سوشي'],
    ['salad','🥗','green','salad|سلطه|سلطة'],
    ['soup','🍲','amber','soup|شوربه|شوربة'],
    ['kebab','🍢','rose','kebab|كباب|كفته|kofta'],
  ]),
  ...family('Cleaning & household', 70, [
    ['laundry-detergent','🧺','blue','laundry detergent|washing powder|ariel|persil|مسحوق غسيل|اريال|برسيل'],
    ['fabric-softener','🧺','rose','fabric softener|downy|منعم ملابس|داوني'],
    ['dishwashing','🧽','green','dishwashing|dish soap|dishwashing liquid|سائل مواعين|صابون مواعين|بريل|fairy'],
    ['dishwasher-tablets','🫧','blue','dishwasher tablets|اقراص غسالة اطباق'],
    ['bleach','🧴','blue','bleach|clorox|كلور|كلوركس'],
    ['disinfectant','🧴','green','disinfectant|dettol|مطهر|ديتول'],
    ['floor-cleaner','🪣','blue','floor cleaner|منظف ارضيات'],
    ['glass-cleaner','🪟','blue','glass cleaner|منظف زجاج'],
    ['toilet-cleaner','🚽','blue','toilet cleaner|harpic|منظف حمام|هاربيك'],
    ['stain-remover','🧴','rose','stain remover|vanish|مزيل بقع|للبقع|فانيش'],
    ['sponge','🧽','amber','sponge|اسفنجه|اسفنجة|ليفة مواعين'],
    ['tissues','🧻','blue','tissue|tissues|مناديل'],
    ['toilet-paper','🧻','blue','toilet paper|ورق تواليت'],
    ['paper-towels','🧻','amber','paper towels|kitchen roll|مناديل مطبخ'],
    ['trash-bags','🗑️','green','trash bags|garbage bags|اكياس قمامه|اكياس زباله'],
    ['foil','🍽️','blue','foil|aluminium foil|aluminum foil|ورق فويل|فويل'],
    ['cling-film','📦','blue','cling film|plastic wrap|plaste roll|stretch film|استرتش|رول بلاستيك'],
    ['baking-paper','📜','amber','baking paper|parchment|ورق زبده'],
    ['food-bags','🛍️','blue','freezer bags|ziplock|اكياس ثلاجه'],
    ['air-freshener','🌸','rose','air freshener|معطر جو'],
    ['insecticide','🦟','green','insecticide|bug spray|مبيد حشري|بيروسول'],
    ['broom','🧹','amber','broom|مقشه|مقشة'],
    ['mop','🪣','blue','mop|ممسحه|ممسحة'],
    ['bucket','🪣','blue','bucket|جردل'],
    ['cleaning-gloves','🧤','green','cleaning gloves|قفازات تنظيف'],
    ['candle','🕯️','amber','candle|candles|شمع'],
    ['matches','🔥','rose','matches|كبريت'],
    ['lighter','🔥','rose','lighter|ولاعه|ولاعة'],
    ['battery','🔋','green','battery|batteries|بطاريه|بطاريات'],
    ['light-bulb','💡','amber','light bulb|led bulb|لمبه|لمبات'],
  ]),
  ...family('Personal care & health', 80, [
    ['shampoo','🧴','green','shampoo|شامبو'],
    ['conditioner','🧴','rose','hair conditioner|conditioner|بلسم'],
    ['hair-mask','🧴','rose','hair mask|ماسك شعر'],
    ['hair-oil','🧴','amber','hair oil|زيت شعر'],
    ['hair-dye','🎨','rose','hair dye|صبغة شعر'],
    ['body-wash','🧴','blue','body wash|shower gel|شاور جل|غسول جسم'],
    ['soap','🧼','green','soap|صابون'],
    ['face-wash','🫧','blue','face wash|facial cleanser|غسول وجه|غسول بشره'],
    ['moisturizer','🧴','rose','moisturizer|moisturiser|مرطب'],
    ['body-lotion','🧴','rose','body lotion|لوشن'],
    ['sunscreen','☀️','amber','sunscreen|sunblock|واقي شمس|صن بلوك'],
    ['serum','💧','blue','serum|سيروم'],
    ['toner','💧','rose','skin toner|facial toner|toner|تونر'],
    ['deodorant','🧴','blue','deodorant|antiperspirant|مزيل عرق'],
    ['perfume','🌸','rose','perfume|cologne|عطر|برفان'],
    ['toothpaste','🪥','blue','toothpaste|معجون اسنان'],
    ['toothbrush','🪥','green','toothbrush|فرشه اسنان'],
    ['mouthwash','🫧','blue','mouthwash|غسول فم|مضمضه'],
    ['dental-floss','🦷','blue','dental floss|خيط اسنان'],
    ['razor','🪒','blue','razor|ماكينه حلاقه|شفرات حلاقه'],
    ['shaving-foam','🪒','blue','shaving foam|shaving cream|رغوة حلاقة'],
    ['lipstick','💄','rose','lipstick|روج'],
    ['makeup','💄','rose','makeup|foundation|mascara|eyeliner|ميكب|مكياج|ماسكرا'],
    ['nail-polish','💅','rose','nail polish|مانيكير'],
    ['cotton-pads','☁️','blue','cotton pads|قطن طبي|قطن مكياج'],
    ['sanitary-pads','🩹','rose','sanitary pads|period pads|فوط صحيه'],
    ['wet-wipes','🧻','blue','wet wipes|مناديل مبلله'],
    ['medicine','💊','rose','medicine|medication|دواء|ادويه|صيدليه'],
    ['vitamins','💊','amber','vitamin|vitamins|supplement|فيتامين|مكمل غذائي'],
    ['painkiller','💊','rose','painkiller|panadol|paracetamol|بنادول|مسكن'],
    ['bandage','🩹','rose','bandage|plaster|ضماده|شاش'],
    ['thermometer','🌡️','rose','thermometer|ترمومتر'],
    ['face-mask','😷','blue','surgical mask|face masks|كمامه|كمامات'],
    ['hand-sanitizer','🫧','green','hand sanitizer|معقم يدين'],
    ['doctor','🩺','blue','doctor|clinic|consultation|كشف دكتور|عياده'],
    ['dentist','🦷','blue','dentist|dental|طبيب اسنان|دكتور اسنان'],
    ['lab-tests','🧪','blue','blood test|lab tests|تحاليل'],
    ['glasses','👓','blue','glasses|نظاره طبيه'],
    ['contact-lenses','👁️','blue','contact lenses|عدسات لاصقه'],
    ['haircut','💇','violet','haircut|barber|حلاق|قص شعر'],
    ['dry-clean','🧺','blue','dry clean|dry cleaning|دراي كلين'],
  ]),
  ...family('Baby & pets', 85, [
    ['diapers','👶','blue','diaper|diapers|nappy|nappies|حفاضات|بامبرز'],
    ['baby-formula','🍼','blue','baby formula|infant formula|لبن اطفال'],
    ['baby-food','🥣','amber','baby food|cerelac|سيريلاك'],
    ['baby-bottle','🍼','blue','baby bottle|ببرونه'],
    ['pacifier','👶','rose','pacifier|لهايه|تتينه'],
    ['stroller','👶','blue','stroller|عربيه اطفال'],
    ['toys','🧸','amber','toy|toys|لعب اطفال'],
    ['cat-food','🐈','amber','cat food|اكل قطط'],
    ['dog-food','🐕','amber','dog food|اكل كلاب'],
    ['pet-food','🐾','amber','pet food|dry food|دراي فود'],
    ['cat-litter','🐈','blue','cat litter|رمل قطط'],
    ['vet','🐾','green','vet|veterinary|بيطري'],
    ['pet-shampoo','🐾','blue','pet shampoo|dog shampoo|cat shampoo|شامبو حيوانات'],
    ['bird-food','🐦','green','bird food|اكل عصافير'],
    ['fish-food','🐠','blue','fish food|اكل سمك زينه'],
  ]),
  ...family('Home, clothing & electronics', 65, [
    ['plate','🍽️','blue','plate|plates|طبق|اطباق'],
    ['bowl','🥣','blue','bowl|bowls|بوله'],
    ['mug','☕','amber','mug|mugs|مج|مجات'],
    ['cutlery','🍴','blue','cutlery|fork|spoon|ملاعق|شوك'],
    ['knife','🔪','blue','kitchen knife|سكينه مطبخ'],
    ['pan','🍳','amber','frying pan|طاسه|مقلاه'],
    ['pot','🍲','amber','cooking pot|حله'],
    ['food-container','🥡','blue','food container|lunch box|علب حفظ|لانش بوكس'],
    ['kettle','🫖','blue','kettle|كاتل|غلايه'],
    ['blender','🔌','green','blender|خلاط'],
    ['air-fryer','🍳','amber','air fryer|اير فراير'],
    ['microwave','🔌','blue','microwave|ميكروويف'],
    ['fridge','🧊','blue','refrigerator|fridge|ثلاجه'],
    ['washing-machine','🧺','blue','washing machine|غساله'],
    ['vacuum','🧹','blue','vacuum cleaner|مكنسه كهربائيه'],
    ['air-conditioner','❄️','blue','air conditioner|تكييف',90],
    ['fan','🌬️','blue','electric fan|مروحه'],
    ['iron','👔','blue','clothes iron|مكواه'],
    ['towel','🧺','blue','towel|towels|فوطه|فوط'],
    ['bedsheet','🛏️','blue','bedsheet|bed sheet|ملايه'],
    ['pillow','🛏️','violet','pillow|مخده'],
    ['blanket','🛏️','violet','blanket|بطانيه'],
    ['curtains','🪟','violet','curtain|curtains|ستاير'],
    ['carpet','🏠','amber','carpet|rug|سجاده'],
    ['furniture','🛋️','amber','furniture|sofa|اثاث|كنبه'],
    ['chair','🪑','amber','chair|كرسي'],
    ['shirt','👕','blue','shirt|tshirt|t shirt|تيشيرت|قميص'],
    ['jeans','👖','blue','jeans|trousers|pants|بنطلون|جينز'],
    ['dress','👗','rose','dress|فستان'],
    ['jacket','🧥','amber','jacket|coat|جاكيت|معطف'],
    ['shoes','👟','blue','shoes|sneakers|حذاء|كوتشي|جزمه'],
    ['socks','🧦','violet','socks|شراب|جوارب'],
    ['underwear','🩲','blue','underwear|ملابس داخليه'],
    ['scarf','🧣','rose','scarf|hijab|طرحه|حجاب'],
    ['bag','👜','amber','handbag|backpack|شنطه'],
    ['watch','⌚','blue','watch|ساعه يد'],
    ['jewellery','💍','amber','jewellery|jewelry|ring|مجوهرات|خاتم'],
    ['phone','📱','blue','phone|smartphone|iphone|موبايل|تليفون'],
    ['phone-case','📱','violet','phone case|screen protector|جراب موبايل|اسكرينه',90],
    ['charger','🔌','blue','charger|شاحن',90],
    ['cable','🔌','blue','usb cable|charging cable|كابل شحن',90],
    ['power-bank','🔋','green','power bank|باور بانك',90],
    ['headphones','🎧','violet','headphones|earbuds|airpods|سماعات'],
    ['laptop','💻','blue','laptop|لاب توب'],
    ['keyboard','⌨️','blue','keyboard|كيبورد'],
    ['mouse','🖱️','blue','computer mouse|ماوس'],
    ['monitor','🖥️','blue','monitor|شاشه كمبيوتر'],
    ['television','📺','blue','television|smart tv|تلفزيون'],
    ['printer','🖨️','blue','printer|طابعه'],
    ['printer-ink','🖨️','violet','printer ink|printer toner|حبر طابعه',90],
    ['router','📶','blue','router|راوتر'],
    ['storage-drive','💾','blue','flash drive|hard drive|ssd|فلاشه|هارد'],
    ['camera','📷','blue','camera|كاميرا'],
    ['game-console','🎮','violet','playstation|xbox|game console|بلايستيشن'],
    ['tools','🛠️','blue','tool kit|screwdriver|hammer|مفك|شاكوش'],
    ['paint','🎨','violet','wall paint|دهانات|بويه'],
    ['plant','🪴','green','houseplant|plant pot|نبات زينه|قصريه زرع'],
    ['flowers','💐','rose','flowers|bouquet|ورد|بوكيه'],
  ]),
  ...family('Services, transport & leisure', 90, [
    ['uber','🚗','blue','uber|careem|didi|indrive|اوبر|كريم|ديدي'],
    ['taxi','🚕','amber','taxi|تاكسي'],
    ['bus','🚌','blue','bus ticket|اتوبيس'],
    ['metro','🚇','blue','metro|subway|مترو'],
    ['train','🚆','blue','train ticket|قطار|تذكره قطر'],
    ['flight','✈️','blue','flight|airline|تذكره طيران'],
    ['fuel','⛽','amber','petrol|gasoline|diesel|fuel|بنزين|سولار'],
    ['parking','🅿️','blue','parking|ركنه|جراج'],
    ['car-wash','🚿','blue','car wash|غسيل عربيه'],
    ['car-service','🔧','blue','car service|car repair|صيانه عربيه'],
    ['engine-oil','🛢️','amber','engine oil|motor oil|زيت موتور'],
    ['tyres','🛞','blue','tyre|tyres|tire|tires|كاوتش'],
    ['toll','🛣️','blue','toll|كارته'],
    ['electricity-bill','💡','amber','electricity bill|فاتوره كهرباء'],
    ['water-bill','🚰','blue','water bill|فاتوره مياه'],
    ['gas-bill','🔥','amber','gas bill|فاتوره غاز'],
    ['internet','📶','blue','internet|adsl|wifi|broadband|انترنت|اشتراك نت'],
    ['mobile-plan','📱','blue','mobile bill|phone bill|recharge|شحن رصيد|باقه موبايل'],
    ['rent','🏠','amber','rent|ايجار'],
    ['maintenance','🛠️','blue','maintenance|صيانه'],
    ['plumber','🔧','blue','plumber|سباك'],
    ['electrician','🔌','amber','electrician|كهربائي'],
    ['cleaning-service','🧹','green','cleaning service|خدمه تنظيف'],
    ['delivery','📦','amber','delivery fee|shipping fee|مصاريف شحن|رسوم توصيل'],
    ['charity','🤲','green','charity|donation|تبرع|صدقه|زكاه'],
    ['insurance','🛡️','blue','insurance|تامين'],
    ['bank-fee','🏦','blue','bank fee|عموله بنك'],
    ['school','🎒','amber','school fees|مصروفات مدرسه'],
    ['course','🎓','blue','course|tuition|كورس|دروس'],
    ['books','📚','amber','book|books|كتاب|كتب'],
    ['notebook','📓','blue','notebook|كشكول|كراسه'],
    ['stationery','✏️','amber','stationery|pen|pencil|قلم|اقلام'],
    ['printing','🖨️','blue','printing|photocopy|طباعه|تصوير ورق'],
    ['cinema','🎬','violet','cinema|movie ticket|سينما'],
    ['concert','🎵','violet','concert|حفله'],
    ['gym','🏋️','green','gym|جيم|اشتراك نادي'],
    ['football','⚽','green','football|كره قدم|حجز ملعب'],
    ['swimming','🏊','blue','swimming|سباحه'],
    ['hotel','🏨','violet','hotel|فندق'],
    ['travel','🧳','blue','travel|vacation|رحله|سفر'],
    ['restaurant','🍽️','amber','restaurant|مطعم'],
    ['subscription','🔁','violet','subscription|اشتراك'],
    ['streaming','🎬','violet','netflix|shahid|watch it|osn|نتفليكس|شاهد'],
    ['music','🎵','violet','spotify|apple music|انغامي'],
    ['gift','🎁','rose','gift|هديه|هدايا'],
    ['cigarettes','🚬','amber','cigarettes|marlboro|سجائر|مارلبورو'],
  ]),
]
